//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class productcreator
    {
        public int creatorID { get; set; }
        public int productID { get; set; }
        public string creatorRole { get; set; }
    
        public virtual creator creator { get; set; }
        public virtual product product { get; set; }
    }
}
