//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard
    {
        public int creditCardID { get; set; }
        public Nullable<int> creditCardNumber { get; set; }
        public Nullable<int> creditCardCVV { get; set; }
        public Nullable<float> creditBalance { get; set; }
        public string cardProvider { get; set; }
        public string creditCardHolderName { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int userID { get; set; }
    
        public virtual user user { get; set; }
    }
}
