//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int logID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> timeStamp { get; set; }
        public string logMessage { get; set; }
    }
}
