//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class musicShopEntities : DbContext
    {
        public musicShopEntities()
            : base("name=musicShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cartdetail> cartdetails { get; set; }
        public virtual DbSet<creator> creators { get; set; }
        public virtual DbSet<creditcard> creditcards { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<invoicedetail> invoicedetails { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productcreator> productcreators { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<log> logs { get; set; }
    }
}
