//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cartdetails = new HashSet<cartdetail>();
            this.invoicedetails = new HashSet<invoicedetail>();
            this.productcreators = new HashSet<productcreator>();
            this.ratings = new HashSet<rating>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public Nullable<float> productPrice { get; set; }
        public string productCover { get; set; }
        public int productTypeID { get; set; }
        public Nullable<int> genreID { get; set; }
        public Nullable<bool> isDiscounted { get; set; }
        public Nullable<float> discountRate { get; set; }
        public string productFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartdetail> cartdetails { get; set; }
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicedetail> invoicedetails { get; set; }
        public virtual producttype producttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productcreator> productcreators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
    }
}
